// examples/vite/src/views/Home.vue
<template>
  <div>
    <HelloWorld msg="Vue3 + vite示例"></HelloWorld>
    <div class="content" style="text-align: center">
      <p>
        当前vite版本
        <el-tag style="vertical-align: text-top" size="small">2.7.2</el-tag>
      </p>
      <p>
        当前vue版本
        <el-tag style="vertical-align: text-top" size="small">3.2.26</el-tag>
      </p>
      <p>
        当前element-plus版本
        <el-tag style="vertical-align: text-top" size="small">2.2.6</el-tag>
      </p>
      <p>
        当前ant-design-vue版本
        <el-tag style="vertical-align: text-top" size="small">2.2.8</el-tag>
      </p>
      <p>
        <el-button @click="handleOpen">仓库地址</el-button>
      </p>
    </div>
  </div>
</template>

<script>
import HelloWorld from '../components/HelloWorld.vue';
export default {
  components: {
    HelloWorld,
  },
  methods: {
    handleOpen() {
      window.open('https://github.com/WeMadeCode/jieshu/tree/master/examples/vite');
    },
  },
};
</script>

<style>
:root {
  --host-color: #f16b5f;
}
</style>

// examples/react18/src/pages/Home.tsx
import { version } from 'react';
import Tag from 'antd/es/tag';
import Button from 'antd/es/button';
import antdVersion from 'antd/es/version';

const Home = () => (
  <section>
    <h2>React18 示例</h2>
    <p className="stack">Vite + TypeScript + React {version}</p>
    <p>
      当前 React 版本 <Tag color="blue">{version}</Tag>
    </p>
    <p>
      当前 Ant Design 版本 <Tag color="geekblue">{antdVersion}</Tag>
    </p>
    <p>{window.__POWERED_BY_JIESHU__ ? '当前运行在界枢微前端环境中' : '当前为独立运行模式'}</p>
    <p>参考 React17 示例：弹窗、路由同步、应用通信和状态保活。</p>
    <Button href="https://github.com/WeMadeCode/jieshu/tree/master/examples/react18" target="_blank" rel="noreferrer">
      仓库地址
    </Button>
  </section>
);

export default Home;
