// examples/vue3/src/App.vue
<template>
  <div id="nav" v-if="$route.name !== 'Postmessage'">
    <router-link to="/home">首页</router-link> | <router-link to="/dialog">弹窗</router-link> |
    <router-link to="/location">路由</router-link> | <router-link to="/contact">通信</router-link> |
    <router-link to="/state">状态</router-link> | <router-link to="/inline-event">内联事件</router-link>
  </div>
  <router-view />
</template>

<script>
export default {
  watch: {
    // 在 vue3-sub 路由下主动告知主应用路由跳转，主应用也跳到相应路由高亮菜单栏
    $route() {
      window.$jieshu?.bus.$emit('sub-route-change', 'vue3', this.$route.path);
    },
  },
  mounted() {
    window.$jieshu?.bus.$on('vue3-router-change', (path) => this.$router.push(path));
  },
};
</script>

// examples/react18/src/App.tsx
import { useEffect, useRef } from 'react';
import { BrowserRouter, NavLink, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import Home from './pages/Home';
import Dialog from './pages/Dialog';
import Location from './pages/Location';
import Communication from './pages/Communication';
import State from './pages/State';

const Navigation = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const ready = useRef(false);

  useEffect(() => {
    const bus = window.$jieshu?.bus;
    const changeRoute = (path: string) => {
      const currentPath = `/${window.location.pathname.slice(import.meta.env.BASE_URL.length)}`;
      if (currentPath !== path) {
        // 主应用已经创建历史记录，同步指令只替换子应用路由，避免前进后退产生重复记录。
        void navigate(path, { replace: true });
      }
    };
    bus?.$on('react18-router-change', changeRoute);
    if (!ready.current) {
      ready.current = true;
      bus?.$emit('react18-router-ready');
    }
    return () => {
      bus?.$off('react18-router-change', changeRoute);
    };
  }, [navigate]);

  useEffect(() => {
    window.$jieshu?.bus.$emit('sub-route-change', 'react18', location.pathname);
    console.log(`react18 ${location.pathname.slice(1)} mounted`);
  }, [location.pathname]);

  return (
    <nav aria-label="React18 子应用导航" className="react18-nav">
      <NavLink to="/home" replace={Boolean(window.$jieshu?.props?.route)}>
        首页
      </NavLink>
      <NavLink to="/dialog" replace={Boolean(window.$jieshu?.props?.route)}>
        弹窗
      </NavLink>
      <NavLink to="/location" replace={Boolean(window.$jieshu?.props?.route)}>
        路由
      </NavLink>
      <NavLink to="/communication" replace={Boolean(window.$jieshu?.props?.route)}>
        通信
      </NavLink>
      <NavLink to="/state" replace={Boolean(window.$jieshu?.props?.route)}>
        状态
      </NavLink>
    </nav>
  );
};

const App = () => (
  <BrowserRouter basename={import.meta.env.BASE_URL}>
    <main className="react18-app">
      <h1>React18 子应用</h1>
      <Navigation />
      <Routes>
        <Route path="/home" element={<Home />} />
        <Route path="/dialog" element={<Dialog />} />
        <Route path="/location" element={<Location />} />
        <Route path="/communication" element={<Communication />} />
        <Route path="/state" element={<State />} />
        <Route path="*" element={<Navigate to="/home" replace />} />
      </Routes>
    </main>
  </BrowserRouter>
);

export default App;
