// examples/main-react-ts/src/pages/Angular12.tsx
import { useNavigate } from "react-router-dom";

import hostMap from "../hostMap";
import WujieReact from "../wujieReact";

export default function Angular12() {
  const navigate = useNavigate();
  const props = {
    jump: (name: string): void => {
      void navigate(`/${name}`);
    },
  };

  return (
    <WujieReact
      width="100%"
      height="100%"
      name="angular12"
      url={hostMap("//localhost:7400/")}
      sync
      props={props}
    />
  );
}

// examples/main-vue-vite/src/views/Angular12.vue
<template>
  <JieshuVue class="angular-container" name="angular12" :url="url" :attrs="attrs" :sync="true"></JieshuVue>
</template>

<script>
import hostMap from '../hostMap';

export default {
  name: 'Angular12View',
  data() {
    return {
      url: hostMap('//localhost:7400/'),
      // 修正iframe的url，防止github pages csp报错
      attrs: import.meta.env.PROD ? { src: hostMap('//localhost:7400/') } : {},
    };
  },
};
</script>

<style lang="css" scoped>
.angular-container {
  width: 100%;
  height: 100%;
}
</style>
