// examples/main-react-rspack/src/pages/React17.tsx
import { useLocation, useNavigate } from 'react-router-dom';

import hostMap from '../hostMap';
import JieshuReact from '../jieshuReact';

export default function React17() {
  const location = useLocation();
  const navigate = useNavigate();
  const react17Url = hostMap('//localhost:7100/');
  const path = location.pathname.replace('/react17-sub', '').replace('/react17', '');

  if (path) {
    JieshuReact.bus.$emit<[path: string]>('react17-router-change', path);
  }

  const props = {
    jump: (name: string): void => {
      void navigate(`/${name}`);
    },
  };

  return <JieshuReact width="100%" height="100%" name="react17" url={react17Url} sync={!path} props={props} />;
}

// examples/main-vue-vite/src/views/React17.vue
<template>
  <!--保活模式，name相同则复用一个子应用实例，改变url无效，必须采用通信的方式告知路由变化 -->
  <JieshuVue width="100%" height="100%" name="react17" :url="react17Url" :sync="true"></JieshuVue>
</template>

<script>
import hostMap from '../hostMap';
export default {
  name: 'React17View',
  data() {
    return {
      react17Url: hostMap('//localhost:7100/'),
    };
  },
};
</script>

<style scoped></style>
