// examples/main-react-ts/src/pages/React16.tsx
import { useLocation, useNavigate } from "react-router-dom";

import hostMap from "../hostMap";
import WujieReact from "../wujieReact";

export default function React16() {
  const location = useLocation();
  const navigate = useNavigate();
  const path = location.pathname.replace("/react16-sub", "").replace("/react16", "").replace("/", "");
  const react16Url = hostMap("//localhost:7600/") + path;
  const props = {
    jump: (name: string): void => {
      void navigate(`/${name}`);
    },
  };

  return (
    <WujieReact width="100%" height="100%" name="react16" url={react16Url} sync={!path} props={props} />
  );
}

// examples/main-vue-vite/src/views/React16.vue
<template>
  <!--单例模式，name相同则复用一个界枢实例，改变url则子应用重新渲染实例到对应路由 -->
  <JieshuVue width="100%" height="100%" name="react16" :url="react16Url" :sync="true"></JieshuVue>
</template>

<script>
import hostMap from '../hostMap';

export default {
  name: 'React16View',
  data() {
    return {
      react16Url: hostMap('//localhost:7600/'),
    };
  },
};
</script>

<style scoped></style>
