// examples/main-react-ts/src/pages/Vite.tsx
import { useLocation, useNavigate } from "react-router-dom";

import hostMap from "../hostMap";
import WujieReact from "../wujieReact";

export default function Vite() {
  const location = useLocation();
  const navigate = useNavigate();
  const path = location.pathname.replace("/vite-sub", "").replace("/vite", "").replace("/", "");
  const viteUrl = hostMap("//localhost:7500/") + path;
  const props = {
    jump: (name: string): void => {
      void navigate(`/${name}`);
    },
  };

  return <WujieReact width="100%" height="100%" name="vite" url={viteUrl} sync={!path} props={props} />;
}

// examples/main-vue-vite/src/views/Vite.vue
<template>
  <!--单例模式，name相同则复用一个界枢实例，改变url则子应用重新渲染实例到对应路由 -->
  <JieshuVue width="100%" height="100%" name="vite" :url="viteUrl" :sync="true"></JieshuVue>
</template>

<script>
import hostMap from '../hostMap';

export default {
  name: 'ViteView',
  data() {
    return {
      viteUrl: hostMap('//localhost:7500/'),
    };
  },
};
</script>

<style scoped></style>
